sense = sense_hat.SenseHat()
sense.clear()


# Edit these variables to change key game parameters
green_color = (0,255,0)      # RGB color of column pixels
yellow = (255, 255, 0)
blue = (0, 0, 255)
red = (255, 0, 0)
white = (255,255,255)

green = (0, 255, 0)
sense.set_pixel(0,0,green_color)
sense.set_pixel(0,1,green_color)
sense.set_pixel(0,2,green_color)
sense.set_pixel(0,3,green_color)
sense.set_pixel(0,4,green_color)
sense.set_pixel(0,5,green_color)
sense.set_pixel(0,6,green_color)
sense.set_pixel(0,7,green_color)
sense.set_pixel(1,0,green_color)
sense.set_pixel(2,0,green_color)
sense.set_pixel(3,0,green_color)
sense.set_pixel(4,0,green_color)
sense.set_pixel(5,0,green_color)
sense.set_pixel(6,0,green_color)
sense.set_pixel(7,0,green_color)
sense.set_pixel(7,1,green_color)
sense.set_pixel(7,2,green_color)
sense.set_pixel(7,3,green_color)
sense.set_pixel(7,4,green_color)
sense.set_pixel(7,5,green_color)
sense.set_pixel(7,6,green_color)
sense.set_pixel(7,7,green_color)
sense.set_pixel(1,7,green_color)
sense.set_pixel(2,7,green_color)
sense.set_pixel(3,7,green_color)
sense.set_pixel(4,7,green_color)
sense.set_pixel(5,7,green_color)
sense.set_pixel(6,7,green_color)
sense.set_pixel(7,7,green_color)

sense.set_pixel(1,1,yellow)
sense.set_pixel(1,2,yellow)
sense.set_pixel(1,3,yellow)
sense.set_pixel(1,4,yellow)
sense.set_pixel(1,5,yellow)
sense.set_pixel(1,6,yellow)
sense.set_pixel(2,1,yellow)
sense.set_pixel(3,1,yellow)
sense.set_pixel(4,1,yellow)
sense.set_pixel(5,1,yellow)
sense.set_pixel(6,1,yellow)
sense.set_pixel(6,2,yellow)
sense.set_pixel(6,3,yellow)
sense.set_pixel(6,4,yellow)
sense.set_pixel(6,5,yellow)
sense.set_pixel(6,6,yellow)
sense.set_pixel(2,6,yellow)
sense.set_pixel(3,6,yellow)
sense.set_pixel(4,6,yellow)
sense.set_pixel(5,6,yellow)
sense.set_pixel(6,6,yellow)

sense.set_pixel(2,2,blue)
sense.set_pixel(6,2,blue)
sense.set_pixel(6,3,blue)
sense.set_pixel(6,4,blue)
sense.set_pixel(6,5,blue)
sense.set_pixel(2,2,blue)
sense.set_pixel(3,2,blue)
sense.set_pixel(4,2,blue)
sense.set_pixel(5,2,blue)
sense.set_pixel(2,3,blue)
sense.set_pixel(2,4,blue)
sense.set_pixel(2,5,blue)
sense.set_pixel(3,5,blue)
sense.set_pixel(4,5,blue)
sense.set_pixel(5,5,blue)

sense.set_pixel(3,3,white)
sense.set_pixel(4,3,white)
sense.set_pixel(5,3,white)
sense.set_pixel(3,4,white)
sense.set_pixel(4,4,white)
sense.set_pixel(5,4,white)

